title = "Open Container Initiative"
baseURL = "https://opencontainers.org"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "Cloud Native Computing Foundation"

enableGitInfo = true
summaryLength = 15

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = "The **Open Container Initiative** is an open governance structure for the express purpose of creating open industry standards around container formats and runtimes."
herodescription = "Established in June 2015 by Docker and other leaders in the container industry, the OCI currently contains two specifications: the Runtime Specification (runtime-spec) and the Image Specification (image-spec). The Runtime Specification outlines how to run a “filesystem bundle” that is unpacked on disk. At a high-level an OCI implementation would download an OCI Image then unpack that image into an OCI Runtime filesystem bundle. At this point the OCI Runtime Bundle would be run by an OCI Runtime."
copyrightYear = 2020
favicon = "favicon.png"
repositoryUrl = "https://github.com/opencontainers/opencontainers.org"
contentDir = "/content/"

[params.logos]
navbar = "cncf-color.png"

[permalinks]
blog = "/blog/:year/:01/:02/:title/"

[[params.colors.extra]]
name = "twitter-blue"
hex = "#00aced"

[[params.social]]
name = "Twitter"
color = "twitter-blue"
url = "https://twitter.com/oci_org"
icon = "fab fa-twitter"

[[params.fonts]]
name = "Fira Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Fire Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"


[[menu.main]]
name = "About"
identifier ="about"
url = "#"
weight = 10

[[menu.main]]
name = "Governance"
parent = "about"
url = "https://github.com/opencontainers/tob/blob/master/CHARTER.md"
post = "external"
weight = 30

[[menu.main]]
name = "Code of conduct"
parent = "about"
url = "https://github.com/opencontainers/.github/blob/master/CODE_OF_CONDUCT.md"
post = "external"
weight = 40

[[menu.main]]
name = "Leadership and oversight"
parent = "about"
url = "/about/tob"
weight = 50

[[menu.main]]
name = "Security disclosure"
parent = "about"
url = "/about/security-disclosure"
weight = 70

[[menu.main]]
name = "Community"
identifier ="community"
url = "#"
weight = 20

[[menu.main]]
name = "Overview"
parent ="community"
url = "/community/overview"
weight = 10

[[menu.main]]
name = "Certification program"
parent = "community"
url = "/community/certified"
weight = 20

[[menu.main]]
name = "Join"
identifier ="join"
url = "/join"
weight = 30

[[menu.main]]
name = "Blog"
identifier ="blog"
url = "/blog"
weight = 40

[[menu.main]]
name = "News"
identifier ="news"
url = "#"
weight = 50

[[menu.main]]
name = "Announcements"
parent ="news"
url = "/announcements/"
weight = 10

[[menu.main]]
name = "In the news"
parent ="news"
url = "/news/"
weight = 20

[[menu.main]]
name = "FAQ"
identifier ="faq"
url = "/faq"
weight = 60

[[menu.main]]
name = "Release notices"
identifier ="releases"
url = "/releases"
weight = 80

[[menu.main]]
name = "Contact us"
identifier ="contact"
url = "/contact"
weight = 90
